version: '3'
services:
  develop:
    container_name: "dev"
    env_file:
      - .env
    build:
      context: "."
      dockerfile: "./Dockerfile"
      args:
        UID: ${UID}
        GID: ${GID}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # ports:
    #   - "5000:5000"
    shm_size: "2gb"
    tty: true
    volumes:
      - ~/:/home/dev/
